### ISSUE TITLE
API v3

### ISSUE THREAD

**Issue by lesaff** [somatonic/MailChimpNewsletter#1]
Hi @somatonic, great work with the module!

Are you planning to fully convert this module to Mailchimp API v3 soon?

**Comment by somatonic** [comment]
I was planning, but thing is the API3 doesn't have all functionality. So in some cases 2.0 is needed.

**Comment by lesaff** [comment]
Gotcha. API 2.0 will be deprecated come Dec 31st, and won't be accessible after that.
I will fork your module and try to convert them to 3.0. Other functionalities that are 2.0 only will probably have to be replaced/hidden for now.
